export const messages = {
  ru: {
    workspace: 'РАБОЧЕЕ ПРОСТРАНСТВО', addBoard: 'Создать доску', boards: 'Доски', localPrivate: 'Локально и приватно', localDetails: 'Данные на этом устройстве', settings: 'Настройки', saved: '● Сохранено', saving: '● Сохранение...', saveError: '● Ошибка сохранения', theme: 'Сменить тему', yourBoard: 'ВАША ДОСКА', archive: 'Архив', newTask: 'Новая задача', searchPlaceholder: 'Поиск по задачам...', searchLabel: 'Поиск по задачам', filterPriority: 'Фильтр по приоритету', allPriorities: 'Все приоритеты', urgent: 'Срочно', high: 'Высокий', medium: 'Средний', low: 'Низкий', noPriority: 'Без приоритета', filterTag: 'Фильтр по тегу', allTags: 'Все теги', filterDue: 'Фильтр по сроку', allDates: 'Все сроки', overdue: 'Просрочены', today: 'На сегодня', week: 'В ближайшие 7 дней', noDue: 'Без срока', reset: 'Сбросить', boardLabel: 'Канбан-доска', footer: 'Перетащите задачу, чтобы изменить статус ·', footerNewTask: 'новая задача',
    boardSubtitle: '{tasks} задач · {done} в последней колонке · {columns} статусов', boardStats: '{tasks} активных задач · {overdue} просрочено', openTask: 'Открыть задачу {number}: {title}', openLink: 'Открыть ссылку в браузере', linkOpenError: 'Не удалось открыть ссылку: {error}', limit: 'Лимит задач', count: 'Количество задач', columnSettings: 'Настройки колонки', noMatches: 'Нет задач по фильтру', emptyColumn: 'Пока пусто', addTask: 'Добавить задачу', addStatus: 'Добавить статус', close: 'Закрыть', cancel: 'Отмена',
    newTaskSubtitle: 'Задаче будет присвоен следующий номер', task: 'Задача', title: 'Название', titlePlaceholder: 'Что нужно сделать?', status: 'Статус', createTask: 'Создать задачу', createdOn: 'Создана {date}', description: 'Описание', descriptionPlaceholder: 'Добавьте детали задачи...', link: 'Ссылка', linkPlaceholder: 'https://example.com или example.com', linkHint: 'Нажмите на название или значок ссылки в карточке, чтобы открыть её в браузере.', invalidLink: 'Укажите корректную ссылку http:// или https://', priority: 'Приоритет', due: 'Срок', cardColor: 'Цвет карточки', noColor: 'Без цвета', numberHint: 'Номер задачи {number} сохраняется при переносе', tags: 'Теги', tagsHint: 'Создайте теги в настройках доски', checklist: 'Чек-лист', firstCheck: 'Добавьте первый пункт', newCheck: 'Новый пункт чек-листа', add: 'Добавить', checkDone: 'Выполнено: {text}', deleteCheck: 'Удалить пункт', delete: 'Удалить', restore: 'Восстановить', toArchive: 'В архив', save: 'Сохранить', taskSaved: 'Задача сохранена', taskArchived: 'Задача в архиве', taskRestored: 'Задача восстановлена', taskDeleted: 'Задача удалена', deleteTaskTitle: 'Удалить задачу?', deleteTaskBody: '{number} · {title}. Это действие нельзя отменить.',
    newBoard: 'Новая доска', newBoardSubtitle: 'Отдельное пространство для задач', boardName: 'Название доски', boardPlaceholder: 'Например, Личные проекты', createBoard: 'Создать доску', boardCreated: 'Доска создана', newStatus: 'Новый статус', newStatusSubtitle: 'Колонка появится в конце доски', statusName: 'Название статуса', statusPlaceholder: 'Например, На паузе', color: 'Цвет', archiveCount: '{count} задач', archiveEmpty: 'Архив пуст', returnTask: 'Вернуть', deletePermanent: 'Удалить навсегда', deletePermanentTitle: 'Удалить задачу навсегда?', deletePermanentBody: 'Восстановить её после удаления не получится.',
    boardSection: 'Доска', statusesSection: 'Статусы', noLimit: '∞ без лимита', boardColor: 'Цвет доски', deleteBoard: 'Удалить доску', columnColor: 'Цвет колонки', columnName: 'Название колонки', taskLimit: 'Лимит задач', moveLeft: 'Сдвинуть влево', moveRight: 'Сдвинуть вправо', deleteColumn: 'Удалить колонку', newStatusPlaceholder: 'Новый статус', tagColor: 'Цвет тега', tagName: 'Название тега', deleteTag: 'Удалить тег', noTags: 'Тегов пока нет', newTag: 'Новый тег', data: 'Данные', exportJson: 'Экспорт JSON', importJson: 'Импорт JSON', dataNote: 'Данные сохраняются автоматически в папке приложения на этом устройстве. Экспортируйте файл JSON для резервной копии или переноса.', dataPath: 'Файл данных: {path}', done: 'Готово', deleteBoardTitle: 'Удалить доску?', deleteBoardBody: 'Доска «{name}» и все её задачи будут удалены без возможности восстановления.', deleteStatusTitle: 'Удалить статус?', deleteStatusBody: 'Задачи из «{name}» перейдут в другую колонку.', backupSaved: 'Резервная копия сохранена', exportError: 'Ошибка экспорта: {error}', importTitle: 'Импортировать данные?', importBody: 'Текущие данные будут заменены содержимым выбранного файла. Сделайте экспорт, если нужна копия.', chooseFile: 'Выбрать файл', imported: 'Данные импортированы', importError: 'Ошибка импорта: {error}', recovered: 'Данные восстановлены из резервной копии', loadError: '● Ошибка загрузки', loadErrorToast: 'Не удалось загрузить данные: {error}', saveErrorToast: 'Не удалось сохранить: {error}',
    indigo: 'Индиго', mint: 'Мята', amber: 'Янтарь', rose: 'Роза', lilac: 'Сирень', blue: 'Голубой'
  },
  en: {
    workspace: 'WORKSPACE', addBoard: 'Create board', boards: 'Boards', localPrivate: 'Local and private', localDetails: 'Data stays on this device', settings: 'Settings', saved: '● Saved', saving: '● Saving...', saveError: '● Save failed', theme: 'Change theme', yourBoard: 'YOUR BOARD', archive: 'Archive', newTask: 'New task', searchPlaceholder: 'Search tasks...', searchLabel: 'Search tasks', filterPriority: 'Filter by priority', allPriorities: 'All priorities', urgent: 'Urgent', high: 'High', medium: 'Medium', low: 'Low', noPriority: 'No priority', filterTag: 'Filter by tag', allTags: 'All tags', filterDue: 'Filter by due date', allDates: 'All due dates', overdue: 'Overdue', today: 'Due today', week: 'Next 7 days', noDue: 'No due date', reset: 'Reset', boardLabel: 'Kanban board', footer: 'Drag a task to change its status ·', footerNewTask: 'new task',
    boardSubtitle: '{tasks} tasks · {done} in the last column · {columns} statuses', boardStats: '{tasks} active tasks · {overdue} overdue', openTask: 'Open task {number}: {title}', openLink: 'Open link in browser', linkOpenError: 'Could not open link: {error}', limit: 'Task limit', count: 'Task count', columnSettings: 'Column settings', noMatches: 'No matching tasks', emptyColumn: 'No tasks yet', addTask: 'Add task', addStatus: 'Add status', close: 'Close', cancel: 'Cancel',
    newTaskSubtitle: 'The next task number will be assigned', task: 'Task', title: 'Title', titlePlaceholder: 'What needs to be done?', status: 'Status', createTask: 'Create task', createdOn: 'Created {date}', description: 'Description', descriptionPlaceholder: 'Add task details...', link: 'Link', linkPlaceholder: 'https://example.com or example.com', linkHint: 'Click the task title or link icon on its card to open the link in your browser.', invalidLink: 'Enter a valid http:// or https:// link', priority: 'Priority', due: 'Due date', cardColor: 'Card color', noColor: 'No color', numberHint: 'Task number {number} is kept when moved', tags: 'Tags', tagsHint: 'Create tags in board settings', checklist: 'Checklist', firstCheck: 'Add the first item', newCheck: 'New checklist item', add: 'Add', checkDone: 'Done: {text}', deleteCheck: 'Delete item', delete: 'Delete', restore: 'Restore', toArchive: 'Archive', save: 'Save', taskSaved: 'Task saved', taskArchived: 'Task archived', taskRestored: 'Task restored', taskDeleted: 'Task deleted', deleteTaskTitle: 'Delete task?', deleteTaskBody: '{number} · {title}. This cannot be undone.',
    newBoard: 'New board', newBoardSubtitle: 'A separate space for tasks', boardName: 'Board name', boardPlaceholder: 'For example, Personal projects', createBoard: 'Create board', boardCreated: 'Board created', newStatus: 'New status', newStatusSubtitle: 'The column will be added at the end', statusName: 'Status name', statusPlaceholder: 'For example, On hold', color: 'Color', archiveCount: '{count} tasks', archiveEmpty: 'The archive is empty', returnTask: 'Restore', deletePermanent: 'Delete permanently', deletePermanentTitle: 'Delete task permanently?', deletePermanentBody: 'You cannot restore it after deletion.',
    boardSection: 'Board', statusesSection: 'Statuses', noLimit: '∞ no limit', boardColor: 'Board color', deleteBoard: 'Delete board', columnColor: 'Column color', columnName: 'Column name', taskLimit: 'Task limit', moveLeft: 'Move left', moveRight: 'Move right', deleteColumn: 'Delete column', newStatusPlaceholder: 'New status', tagColor: 'Tag color', tagName: 'Tag name', deleteTag: 'Delete tag', noTags: 'No tags yet', newTag: 'New tag', data: 'Data', exportJson: 'Export JSON', importJson: 'Import JSON', dataNote: 'Data is saved automatically in this app’s folder on this device. Export a JSON file for backup or transfer.', dataPath: 'Data file: {path}', done: 'Done', deleteBoardTitle: 'Delete board?', deleteBoardBody: 'Board “{name}” and all its tasks will be deleted permanently.', deleteStatusTitle: 'Delete status?', deleteStatusBody: 'Tasks in “{name}” will move to another column.', backupSaved: 'Backup saved', exportError: 'Export failed: {error}', importTitle: 'Import data?', importBody: 'Current boards will be replaced by the selected file. Export a backup first if needed.', chooseFile: 'Choose file', imported: 'Data imported', importError: 'Import failed: {error}', recovered: 'Data restored from backup', loadError: '● Load failed', loadErrorToast: 'Could not load data: {error}', saveErrorToast: 'Could not save: {error}',
    indigo: 'Indigo', mint: 'Mint', amber: 'Amber', rose: 'Rose', lilac: 'Lilac', blue: 'Blue'
  }
};

export function translate(language, key, values = {}) {
  const template = messages[language]?.[key] ?? messages.ru[key] ?? key;
  return template.replace(/\{(\w+)\}/g, (_, name) => String(values[name] ?? ''));
}
